import { emailPreferenceUrl, managementToken, EMAIL_SITE } from './emailTokens'
const escape = (text: string) => text.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
export function reminderEmail(name: string, contactId: string) {
  const preferences = emailPreferenceUrl('manage', managementToken(contactId))
  const start = `${EMAIL_SITE}/capability-profile/start`
  const text = `Hi ${name},\n\nYour capability check-in\n\nYou asked for a reminder around 75 days after requesting your profile. Take a fresh look at what has changed in your decisions, resources, capacity, and follow-through.\n\nRetake your profile: ${start}\n\nCompare the result with your saved copy and concrete evidence of changed behavior. Scores describe self-reported patterns, not independently verified ability. Your earlier results are stored only in the browser where you completed them.\n\nThis is your one requested reminder. No further reminder is scheduled.\n\nManage email preferences: ${preferences}\n\nQuestions? Reply to hello@iamneilgreene.com.`
  const html = `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><title>Your capability check-in</title></head><body style="margin:0;background:#e6e0d4;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:24px 12px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#faf7f3;"><tr><td bgcolor="#101720" style="padding:28px 24px;color:#faf7f3;"><p style="font:22px Georgia,serif;">Neil Greene.</p><h1 style="font:36px/1.2 Georgia,serif;">Your capability check-in</h1></td></tr><tr><td style="padding:28px 24px;font:16px/1.7 Arial,sans-serif;color:#2b3746;"><p>Hi ${escape(name)},</p><p>You asked for a reminder around 75 days after requesting your profile. Take a fresh look at what has changed in your decisions, resources, capacity, and follow-through.</p><p><a href="${start}" style="display:inline-block;background:#214da8;color:#faf7f3;padding:14px 20px;text-decoration:none;font-weight:bold;">Retake your profile</a></p><p>Compare the result with your saved copy and concrete evidence of changed behavior. Scores describe self-reported patterns, not independently verified ability. Your earlier results are stored only in the browser where you completed them.</p><p>This is your one requested reminder. No further reminder is scheduled.</p><p><a href="${escape(preferences)}" style="color:#214da8;">Manage email preferences</a></p><p>Questions? Reply to hello@iamneilgreene.com.</p></td></tr></table></td></tr></table></body></html>`
  return { text, html }
}
